name: immortalscreen
description: Make screen immortal
version: 0.0.1
author:
  - XuanLoc xuanlocle2412@gmail.com
homepage: https://github.com/xuanlocle/immortalscreen

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.xuanlocle.immortalscreen
    pluginClass: ImmortalScreenPlugin
